url: https://br-web.io/baf
livereload: false
collections_dir: collections
collections:
  become_freelancer:
    output: true
  become_web_designer:
    output: true
    title: Become a web designer
  become_writer:
    output: true

excerpt_separator: <!--more-->
title: Become a Freelancer
#image-path: assets/images/logo@2x.png
image-alt: Become a Freelancer logo
description: Simply how to become a freelancer. Focussing on how to become a writer or web designer.
exclude: [assets/css, gruntfile.js, package.json, node_modules]
keep_files: [assets/css]
include: [_pages, _guides]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag